-- ==========================================
-- Migration: 022_convert_content_projects.sql
-- Description: Cập nhật 9 dự án tiêu biểu nhất của MTECH (từ tổng số 66 dự án)
-- ==========================================

-- Xóa dữ liệu cũ và thêm lại 9 dự án MTECH tiêu biểu
DELETE FROM `projects`;

-- Reset AUTO_INCREMENT
ALTER TABLE `projects` AUTO_INCREMENT = 1;

-- Thêm 9 dự án tiêu biểu nhất của MTECH
INSERT INTO `projects` 
(`title`, `slug`, `category`, `description`, `content`, `image`, `detail_image`, 
 `client`, `location`, `project_date`, `status`, `status_label`, `sort_order`,
 `what_we_did_title`, `what_we_did`, `what_we_did_image`,
 `results_title`, `results`, `result_items`, `tags`, `live_demo`) 
VALUES 

-- 1. Nhà máy Thép xanh Xuân Thiện Nam Định (Lớn nhất - 7,5 triệu tấn/năm)
('Nhà máy Thép xanh Xuân Thiện Nam Định', 
 'nha-may-thep-xanh-xuan-thien-nam-dinh', 
 'Mechanical Engineering',
 'Siêu dự án thép xanh công suất 7.500.000 tấn sản phẩm/năm - lớn nhất Việt Nam',
 '<p>Nhà máy Thép xanh Xuân Thiện Nam Định là siêu dự án luyện kim lớn nhất Việt Nam với công suất 7.500.000 tấn sản phẩm/năm, sử dụng công nghệ sản xuất thép xanh hiện đại nhất thế giới, thân thiện với môi trường.</p><p>MTECH đảm nhận vai trò tư vấn thiết kế cơ sở và giám sát thi công các hạng mục chính của nhà máy, từ hệ thống lò cao đến dây chuyền cán thép hiện đại.</p>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/pr_1-1.jpg',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_1.jpg',
 'Công ty CP Thép Xuân Thiện Nam Định',
 'Nam Định',
 '2026-01-01',
 1,
 'Hoàn thành',
 1,
 'Những gì chúng tôi đã làm',
 '<p>MTECH cung cấp dịch vụ tư vấn kỹ thuật toàn diện và giám sát thi công cho siêu dự án thép xanh quy mô lớn nhất Việt Nam.</p><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Tư vấn thiết kế cơ sở</h5><p>Lập thiết kế cơ sở cho toàn bộ nhà máy, bao gồm hệ thống lò cao, máy cán thép, hệ thống xử lý khí thải và nhà xưởng sản xuất.</p></div><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Giám sát lắp đặt thiết bị</h5><p>Giám sát lắp đặt thiết bị công nghệ cao nhập khẩu từ châu Âu và Nhật Bản, đảm bảo đúng tiêu chuẩn kỹ thuật khắt khe nhất.</p></div>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_2.jpg',
 'Kết quả đạt được',
 '<p>Dự án đã hoàn thành và đi vào vận hành thương mại, trở thành một trong những nhà máy thép hiện đại và lớn nhất khu vực Đông Nam Á.</p><p>Công nghệ sản xuất thép xanh giúp giảm 40% lượng khí thải CO2 so với công nghệ truyền thống, đạt tiêu chuẩn môi trường quốc tế.</p>',
 '["Công suất 7.500.000 tấn/năm", "Công nghệ xanh hiện đại", "Giảm 40% khí thải CO2", "Top đầu Đông Nam Á"]',
 'thép xanh, luyện kim, công nghiệp nặng, siêu dự án',
 ''),

-- 2. Nhà máy xi măng Xuân Thành Line 3 (5 triệu tấn/năm)
('Nhà máy xi măng Xuân Thành Line 3', 
 'nha-may-xi-mang-xuan-thanh-line-3', 
 'Material Engineering',
 'Dây chuyền sản xuất xi măng công suất 5.000.000 tấn/năm tại Hà Nam',
 '<p>Dự án Nhà máy xi măng Xuân Thành Line 3 là dự án trọng điểm của MTECH với công suất 5.000.000 tấn xi măng/năm, một trong những dây chuyền xi măng lớn nhất Việt Nam.</p><p>MTECH đảm nhận vai trò tư vấn thiết kế chi tiết và giám sát thi công toàn bộ dây chuyền sản xuất, từ khâu nghiền nguyên liệu đến đóng bao thành phẩm.</p>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/pr_2-1.jpg',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_1.jpg',
 'Công ty CP xi măng Xuân Thành HN',
 'Hà Nam',
 '2023-01-15',
 1,
 'Hoàn thành',
 2,
 'Những gì chúng tôi đã làm',
 '<p>MTECH đã thực hiện tư vấn thiết kế kỹ thuật chi tiết và giám sát thi công xây dựng, lắp đặt thiết bị cho dây chuyền sản xuất xi măng Line 3.</p><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Thiết kế kỹ thuật</h5><p>Lập thiết kế kỹ thuật chi tiết cho hệ thống lò quay, máy nghiền liệu, máy nghiền xi măng, silo chứa và hệ thống điều khiển tự động DCS.</p></div><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Giám sát thi công</h5><p>Giám sát chặt chẽ quá trình thi công xây dựng và lắp đặt thiết bị, đảm bảo chất lượng, tiến độ và an toàn lao động.</p></div>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_2.jpg',
 'Kết quả đạt được',
 '<p>Dự án đã hoàn thành đúng tiến độ và đạt chất lượng cao. Nhà máy đi vào vận hành ổn định, đạt công suất thiết kế 5 triệu tấn/năm.</p><p>Công nghệ hiện đại giúp giảm tiêu hao năng lượng 15% và bảo vệ môi trường, đạt các tiêu chuẩn khí thải khắt khe của Việt Nam và quốc tế.</p>',
 '["Công suất 5.000.000 tấn/năm", "Vận hành ổn định", "Tiết kiệm 15% năng lượng", "Đạt tiêu chuẩn quốc tế"]',
 'xi măng, công nghiệp, xây dựng, dây chuyền sản xuất',
 ''),

-- 3. Nhà máy xi măng Sông Lam Giai đoạn 2 (5 triệu tấn/năm)
('Nhà máy xi măng Sông Lam Giai đoạn 2', 
 'nha-may-xi-mang-song-lam-giai-doan-2', 
 'Material Engineering',
 'Dây chuyền sản xuất xi măng công suất 5.000.000 tấn/năm tại Nghệ An',
 '<p>Dự án Nhà máy xi măng Sông Lam Giai đoạn 2 là dự án mở rộng quy mô lớn với công suất 5.000.000 tấn/năm tại Nghệ An, nâng tổng công suất nhà máy lên 10 triệu tấn/năm.</p><p>MTECH tham gia tư vấn thiết kế kỹ thuật và giám sát thi công toàn bộ dự án, từ khâu thiết kế đến lắp đặt thiết bị và vận hành thử.</p>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/pr_3-1.jpg',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_1.jpg',
 'Công ty CP xi măng Sông Lam',
 'Nghệ An',
 '2022-05-01',
 1,
 'Hoàn thành',
 3,
 'Những gì chúng tôi đã làm',
 '<p>MTECH đảm nhận tư vấn thiết kế kỹ thuật chi tiết và giám sát thi công cho dự án giai đoạn 2 của Nhà máy xi măng Sông Lam.</p><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Thiết kế kỹ thuật</h5><p>Thiết kế chi tiết hệ thống lò quay φ4,8x72m, máy nghiền liệu, máy nghiền xi măng và hệ thống điều khiển DCS tích hợp.</p></div><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Vận hành thử & chuyển giao</h5><p>Hỗ trợ chủ đầu tư trong giai đoạn vận hành thử, hiệu chỉnh thông số kỹ thuật và chuyển giao công nghệ cho vận hành thương mại.</p></div>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_2.jpg',
 'Kết quả đạt được',
 '<p>Dự án đã hoàn thành đúng tiến độ và ngân sách. Nhà máy đi vào vận hành thương mại sớm hơn dự kiến 3 tháng.</p><p>Tổng công suất hai giai đoạn đạt 10 triệu tấn/năm, đưa Sông Lam trở thành một trong những nhà máy xi măng lớn nhất miền Trung và cả nước.</p>',
 '["Công suất 5.000.000 tấn/năm", "Hoàn thành đúng tiến độ", "Vận hành sớm 3 tháng", "Tổng công suất 10 triệu tấn/năm"]',
 'xi măng, công nghiệp, miền Trung, mở rộng',
 ''),

-- 4. Nhà máy xi măng Minh Tâm (5 triệu tấn/năm)
('Nhà máy xi măng Minh Tâm', 
 'nha-may-xi-mang-minh-tam', 
 'Material Engineering',
 'Dây chuyền sản xuất xi măng công suất 5.000.000 tấn/năm tại Bình Phước',
 '<p>Nhà máy xi măng Minh Tâm là dự án xi măng quy mô lớn tại Bình Phước với công suất 5.000.000 tấn/năm, phục vụ thị trường miền Nam và xuất khẩu.</p><p>MTECH tham gia tư vấn đấu thầu và thiết kế cơ sở cho toàn bộ dự án, đảm bảo công nghệ hiện đại và hiệu quả đầu tư.</p>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/pr_4-1.jpg',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_1.jpg',
 'CTCP Tập đoàn Thai Group',
 'Bình Phước',
 '2016-06-01',
 1,
 'Hoàn thành',
 4,
 'Những gì chúng tôi đã làm',
 '<p>MTECH thực hiện tư vấn đấu thầu và thiết kế cơ sở cho nhà máy xi măng quy mô lớn tại khu vực miền Nam.</p><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Tư vấn đấu thầu</h5><p>Tư vấn lựa chọn nhà thầu EPC, đánh giá công nghệ và thiết bị, đàm phán hợp đồng để đảm bảo chất lượng và tiến độ dự án.</p></div><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Thiết kế cơ sở</h5><p>Lập thiết kế cơ sở cho toàn bộ nhà máy, bao gồm công nghệ sản xuất, bố trí mặt bằng và hệ thống hạ tầng kỹ thuật.</p></div>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_2.jpg',
 'Kết quả đạt được',
 '<p>Dự án đã hoàn thành và đi vào vận hành thành công, đạt công suất thiết kế 5 triệu tấn/năm.</p><p>Nhà máy xi măng Minh Tâm góp phần đáp ứng nhu cầu xi măng cho thị trường miền Nam và xuất khẩu sang Campuchia, Lào.</p>',
 '["Công suất 5.000.000 tấn/năm", "Thị trường miền Nam", "Xuất khẩu Campuchia, Lào", "Công nghệ hiện đại"]',
 'xi măng, công nghiệp, miền Nam, xuất khẩu',
 ''),

-- 5. Nhà máy xi măng Hà Tiên Kiên Lương (4 triệu tấn/năm)
('Nhà máy xi măng Hà Tiên Kiên Lương', 
 'nha-may-xi-mang-ha-tien-kien-luong', 
 'Material Engineering',
 'Dây chuyền sản xuất xi măng công suất 4.000.000 tấn/năm tại Kiên Giang',
 '<p>Nhà máy xi măng Hà Tiên Kiên Lương là dự án xi măng quy mô lớn tại Kiên Giang với công suất 4.000.000 tấn/năm, phục vụ thị trường miền Tây Nam Bộ và xuất khẩu.</p><p>MTECH đảm nhận lập quy hoạch xây dựng và thiết kế cơ sở cho toàn bộ dự án, từ khâu khảo sát địa chất đến thiết kế tổng thể.</p>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/pr_5-1.jpg',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_1.jpg',
 'Công ty CP xi măng Hà Tiên Kiên Lương',
 'Kiên Giang',
 '2026-01-01',
 1,
 'Đang thực hiện',
 5,
 'Những gì chúng tôi đã làm',
 '<p>MTECH thực hiện lập quy hoạch xây dựng và thiết kế cơ sở cho nhà máy xi măng tại khu vực ven biển Kiên Giang.</p><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Lập quy hoạch xây dựng</h5><p>Lập quy hoạch xây dựng chi tiết trên diện tích 60 ha, bao gồm khu sản xuất, kho chứa, cảng biển và hệ thống hạ tầng kỹ thuật.</p></div><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Thiết kế cơ sở</h5><p>Thiết kế cơ sở cho dây chuyền sản xuất xi măng 4 triệu tấn/năm, tích hợp cảng biển để vận chuyển clinker và xi măng.</p></div>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_2.jpg',
 'Kết quả đạt được',
 '<p>Dự án đang trong giai đoạn thi công, dự kiến hoàn thành và đi vào vận hành trong năm 2026.</p><p>Sau khi hoàn thành, nhà máy sẽ trở thành một trong những trung tâm sản xuất xi măng lớn nhất khu vực Đồng bằng sông Cửu Long, phục vụ thị trường miền Tây và xuất khẩu qua đường biển.</p>',
 '["Công suất 4.000.000 tấn/năm", "Quy mô 60 ha", "Tích hợp cảng biển", "Phục vụ miền Tây & xuất khẩu"]',
 'xi măng, công nghiệp, miền Tây, cảng biển',
 ''),

-- 6. Khu nông nghiệp CNC Xuân Thiện Cư M\'gar (3.417 ha - lớn nhất VN)
('Khu nông nghiệp CNC Xuân Thiện Cư M\'gar', 
 'khu-nong-nghiep-cnc-xuan-thien-cu-mgar', 
 'Architecture Engineering',
 'Khu nông nghiệp ứng dụng công nghệ cao quy mô 3.417,0 ha - lớn nhất Việt Nam tại Đắk Lắk',
 '<p>Khu nông nghiệp ứng dụng công nghệ cao Xuân Thiện Cư M\'gar là dự án nông nghiệp quy mô lớn nhất Việt Nam với diện tích 3.417 ha tại Đắk Lắk, ứng dụng công nghệ Israel và Nhật Bản.</p><p>MTECH đảm nhận lập quy hoạch xây dựng và thiết kế cơ sở hạ tầng, hệ thống tưới tiêu công nghệ cao và các công trình phụ trợ.</p>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/pr_6-1.jpg',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_1.jpg',
 'Công ty TNHH Xuân Thiện Đắk Lắk',
 'Đắk Lắk',
 '2023-09-01',
 1,
 'Hoàn thành',
 6,
 'Những gì chúng tôi đã làm',
 '<p>MTECH thực hiện lập quy hoạch và thiết kế cơ sở hạ tầng, hệ thống tưới tiêu công nghệ cao cho khu nông nghiệp quy mô lớn nhất Việt Nam.</p><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Quy hoạch tổng thể</h5><p>Lập quy hoạch tổng thể khu nông nghiệp 3.417 ha, bao gồm vùng sản xuất nông nghiệp, kho lạnh, nhà máy chế biến, trung tâm logistics và hệ thống giao thông nội bộ.</p></div><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Tưới tiêu công nghệ cao</h5><p>Thiết kế hệ thống tưới nhỏ giọt và phun mưa tự động công nghệ Israel, tiết kiệm 50% nước và tăng 30% năng suất so với tưới truyền thống.</p></div>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_2.jpg',
 'Kết quả đạt được',
 '<p>Khu nông nghiệp đã đi vào vận hành, sản xuất các loại nông sản sạch, đạt tiêu chuẩn VietGAP và GlobalGAP, xuất khẩu sang Nhật Bản, Hàn Quốc, châu Âu.</p><p>Hệ thống tưới tiêu công nghệ cao giúp tiết kiệm 50% nước và tăng năng suất 30%, tạo mô hình nông nghiệp bền vững, thân thiện môi trường.</p>',
 '["Quy mô 3.417 ha - lớn nhất VN", "Nông nghiệp công nghệ cao", "Tiết kiệm 50% nước", "Chứng nhận VietGAP, GlobalGAP"]',
 'nông nghiệp, công nghệ cao, bền vững, xuất khẩu',
 ''),

-- 7. Nhà máy Thép xanh Xuân Thiện Nghĩa Hưng (2,5 triệu tấn/năm)
('Nhà máy Thép xanh Xuân Thiện Nghĩa Hưng', 
 'nha-may-thep-xanh-xuan-thien-nghia-hung', 
 'Mechanical Engineering',
 'Nhà máy thép xanh công suất 2.500.000 tấn sản phẩm/năm tại Nam Định',
 '<p>Nhà máy Thép xanh Xuân Thiện Nghĩa Hưng là dự án thép xanh quy mô lớn tại Nam Định với công suất 2.500.000 tấn sản phẩm/năm, sử dụng công nghệ sản xuất thép hiện đại.</p><p>MTECH tham gia tư vấn thiết kế cơ sở và thiết kế kỹ thuật cho các hạng mục chính của nhà máy.</p>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/pr_7-1.jpg',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_1.jpg',
 'Công ty CP Xuân Thiện Nghĩa Hưng',
 'Nam Định',
 '2025-01-01',
 1,
 'Hoàn thành',
 7,
 'Những gì chúng tôi đã làm',
 '<p>MTECH cung cấp dịch vụ tư vấn thiết kế cơ sở và kỹ thuật cho dự án thép xanh tại khu công nghiệp Nghĩa Hưng.</p><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Thiết kế cơ sở</h5><p>Lập thiết kế cơ sở cho toàn bộ nhà máy trên diện tích 84 ha, bao gồm hệ thống lò điện hồ quang, máy cán thép và hệ thống xử lý khí thải.</p></div><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Thiết kế kỹ thuật</h5><p>Thiết kế kỹ thuật chi tiết cho dây chuyền sản xuất thép, đảm bảo công suất 2,5 triệu tấn/năm và đạt tiêu chuẩn chất lượng JIS, ASTM.</p></div>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_2.jpg',
 'Kết quả đạt được',
 '<p>Dự án đã hoàn thành và đi vào vận hành thương mại, sản xuất thép xây dựng và thép cuộn chất lượng cao.</p><p>Công nghệ sản xuất thép xanh giúp giảm 35% lượng khí thải CO2 và tiết kiệm 20% năng lượng so với công nghệ truyền thống.</p>',
 '["Công suất 2.500.000 tấn/năm", "Công nghệ thép xanh", "Giảm 35% khí thải CO2", "Tiêu chuẩn JIS, ASTM"]',
 'thép xanh, luyện kim, công nghiệp nặng',
 ''),

-- 8. Hệ thống phát điện nhiệt dư NM xi măng Nghi Sơn (18 MW)
('Hệ thống phát điện nhiệt dư NM xi măng Nghi Sơn', 
 'he-thong-phat-dien-nhiet-du-nm-xi-mang-nghi-son', 
 'Power & Energy',
 'Hệ thống tận dụng nhiệt thừa phát điện (WHR) công suất 18,0 MW tại Thanh Hóa',
 '<p>Dự án hệ thống phát điện nhiệt dư (WHR) tại Nhà máy xi măng Nghi Sơn là một trong những dự án năng lượng tái tạo tiêu biểu nhất của MTECH với công suất 18,0 MW.</p><p>Hệ thống tận dụng nhiệt thừa từ khí thải của lò nung xi măng để phát điện, giúp giảm tiêu thụ điện năng từ lưới quốc gia và bảo vệ môi trường.</p>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/pr_8-3.jpg',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_1.jpg',
 'Công ty xi măng Vicem Nghi Sơn',
 'Thanh Hóa',
 '2021-06-01',
 1,
 'Hoàn thành',
 8,
 'Những gì chúng tôi đã làm',
 '<p>MTECH thực hiện vai trò Tổng thầu tư vấn cho dự án phát điện nhiệt dư, từ thiết kế đến giám sát thi công và vận hành thử.</p><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Thiết kế hệ thống WHR</h5><p>Thiết kế hệ thống thu hồi nhiệt từ khí thải lò nung, tuabin phát điện 18 MW và hệ thống điện đấu nối vào lưới điện nhà máy.</p></div><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Tối ưu hiệu suất</h5><p>Tính toán và tối ưu hóa thông số kỹ thuật để đạt hiệu suất phát điện cao nhất từ nguồn nhiệt thừa, đảm bảo hiệu suất trên 20%.</p></div>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_2.jpg',
 'Kết quả đạt được',
 '<p>Hệ thống đã vận hành ổn định, phát điện trung bình 120.000 MWh/năm, đáp ứng 30% nhu cầu điện năng của nhà máy xi măng.</p><p>Giảm phát thải CO2 khoảng 70.000 tấn/năm, góp phần bảo vệ môi trường và đạt các tiêu chuẩn phát triển bền vững (ESG) của Vicem.</p>',
 '["Công suất 18,0 MW", "Phát điện 120.000 MWh/năm", "Giảm 70.000 tấn CO2/năm", "Hiệu suất >20%"]',
 'năng lượng tái tạo, nhiệt dư, phát điện, xanh',
 ''),

-- 9. Nhà máy luyện cán thép DST Nghi Sơn (1,2 triệu tấn/năm)
('Nhà máy luyện cán thép DST Nghi Sơn', 
 'nha-may-luyen-can-thep-dst-nghi-son', 
 'Mechanical Engineering',
 'Nhà máy luyện cán thép công suất 1.200.000 tấn sản phẩm/năm tại Khu kinh tế Nghi Sơn',
 '<p>Nhà máy luyện cán thép DST Nghi Sơn là dự án luyện kim quy mô lớn với công suất 1.200.000 tấn sản phẩm/năm tại Khu kinh tế Nghi Sơn, Thanh Hóa, sử dụng công nghệ lò điện hồ quang và máy cán hiện đại.</p><p>MTECH tham gia tư vấn thiết kế cơ sở và giám sát thi công các hạng mục lò điện hồ quang, máy cán thép và hệ thống xử lý nước tuần hoàn.</p>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/pr_10-1.jpg',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_1.jpg',
 'Công ty CP Gang thép DST Nghi Sơn',
 'Thanh Hóa',
 '2024-01-10',
 1,
 'Hoàn thành',
 9,
 'Những gì chúng tôi đã làm',
 '<p>MTECH cung cấp dịch vụ tư vấn thiết kế cơ sở và giám sát thi công cho nhà máy luyện cán thép quy mô lớn tại Khu kinh tế Nghi Sơn.</p><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Tư vấn thiết kế</h5><p>Thiết kế cơ sở và tư vấn lựa chọn công nghệ lò điện hồ quang 120 tấn, máy cán thép và hệ thống xử lý nước tuần hoàn khép kín.</p></div><div class="pr_item"><span class="dot"></span><h5 class="f_size_18 f_600 title_color">Giám sát chất lượng</h5><p>Giám sát chất lượng thi công và lắp đặt thiết bị nhập khẩu từ châu Âu, đảm bảo đạt tiêu chuẩn JIS Nhật Bản và ASTM Mỹ.</p></div>',
 'https://shtheme.info/demosd/wokrate/wp-content/uploads/2019/12/project_details_2.jpg',
 'Kết quả đạt được',
 '<p>Dự án đã hoàn thành và đi vào vận hành thương mại, sản xuất các loại thép xây dựng và thép cuộn chất lượng cao.</p><p>Sản phẩm đạt tiêu chuẩn JIS Nhật Bản và ASTM Mỹ, được thị trường trong nước và xuất khẩu sang Campuchia, Lào đánh giá cao.</p>',
 '["Công suất 1.200.000 tấn/năm", "Thép xây dựng chất lượng cao", "Tiêu chuẩn JIS và ASTM", "Xuất khẩu thành công"]',
 'luyện kim, thép, công nghiệp nặng, Nghi Sơn',
 '');
